// E:\Projects\web\e-commerce\front-end\src\app\[local]\layout.tsx
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import RecoilProvider from "../RecoilProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Eisa-Ecommerce",
  description: "Generated by Eisa",
  icons: {
    icon: "/EisaShop.png",
  },
};

export default function LocaleLayout({
  params: { local },
  children,
}: {
  params: { local: string };
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ backgroundColor: "#eee" }}>
      <body className={inter.className} style={{ margin: "0" }}>
        <RecoilProvider local={local}>{children}</RecoilProvider>
      </body>
    </html>
  );
}
