import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "../Components/footer/Footer";
import { IntlProvider } from "next-intl";
import Header from "../Components/header/Header";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Eisa-Ecommerce",
  description: "Generated by Eisa",
  icons: {
    icon: "/EisaShop.png",
  },
};

export default function LocaleLayout({
  params: { local },
  children,
}: {
  params: { local: string };
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ backgroundColor: "#eee" }}>
      {/* <IntlProvider messages={messages} locale={local}> */}
      <body className={inter.className}>
        {children}

        <Footer />
      </body>
      {/* </IntlProvider> */}
    </html>
  );
}
