import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eisa-Ecommerce",
  description: "Generated by Eisa",

  icons: {
    icon: "/EisaShop.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: "#eee" }}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
